version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs_api
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: nestjs_api
      JWT_ACCESS_SECRET: your-access-secret-key
      JWT_REFRESH_SECRET: your-refresh-secret-key
    depends_on:
      - db
